### ISSUE TITLE
Specify extra working periods

### ISSUE THREAD

**Issue by YushengLi** [zendesk/biz#103]
The similar situation has already been discussed in Issue #5.

Sometimes when there's a holiday on Tuesday (or Thursday), we tend to set Monday (or Friday) as holidays as well to give people a continuous holidays. And then set the next Saturday as 

In #5, you mentioned that we can directly set business hours for Saturday then set every Saturday that is not a working day as holidays, which will calculate business hours correctly in this case.

But since feeding a lot of holidays into configuration might slow down calculation, and it's not intuitive since Saturday as working day is an exceptional conditions, marking every Saturday as working day seems not an elegant way.

So I am wondering whether there's any possibility that Biz can provide a configuration options for us to set a day that is not originally a business hours as working day.

**Comment by craiglittle** [comment]
Hi, @YushengLi!

This has been a feature request a few times now. No promises, but let me give it another think on the overall feasibility.

**Comment by craiglittle** [comment]
@YushengLi  I wanted to let you know that I just merged a PR to implement this feature: https://github.com/zendesk/biz/pull/109

Check it out, and let me know what you think!
