### ISSUE TITLE
dates.days(0).after returns nil

### ISSUE THREAD

**Issue by lacco** [zendesk/biz#112]
To calculate the next business day as a `Date`, I am using the suggestion from #82 . This is working fine until I try to add a zero duration: `Biz.dates.days(0).after(Date.today)`. I would expect to just return the given date, or to return the next business day if the provided date is on the weekend. Instead, `nil` is returned. Is this expected behavior?

**Comment by craiglittle** [comment]
Thanks for the report, @lacco. I agree; I think we can handle this edge case better.

Given a standard configuration of Monday through Friday as active days, I'd like to get your input on the following outcomes:
```ruby
MONDAY   = Date.new(2017, 8, 28)
SATURDAY = Date.new(2017, 9, 2)

Biz.dates.days(0).after(MONDAY)
# returns Monday, August 28, 2017

Biz.dates.days(1).after(MONDAY)
# returns Tuesday, August 29, 2017

Biz.dates.days(0).after(SATURDAY)
# returns Monday, September 3, 2017

Biz.dates.days(1).after(SATURDAY)
# returns Monday, September 3, 2017
```
I think it's more important to keep the `.days(1)` behavior more coherent than the edge case of `.days(0)`, so that's why I tend to think this is the best way to proceed.

What do you think?

**Comment by lacco** [comment]
Mh, interesting thoughts! To be honest this behaviour is a little counter-intuitive for me, but maybe I am just biased because I was using the business_time gem before. 

Just to be clear, I would expect the last example to behave differently:

```
Biz.dates.days(1).after(SATURDAY)
# returns Tuesday, September 4, 2017
```

I get the logic behind your approach and also can't think of any further edge cases. I would be a little worried about breaking existing code and making it harder to migrate from the business_time gem. But if the general behaviour becomes more intuitive for others, then I am happy to support this!

**Comment by craiglittle** [comment]
@lacco I've cut a new release of `clavius` (`v1.0.3`) that includes support for zeroeth-day calculations. If you update your version of `clavius`, you should be good to go!

(Note: I'm not going to force people to upgrade to the latest `clavius` through releasing a version of `biz` with a modified `gemspec`. I trust that if people want this minor change in behavior they'll upgrade themselves or pick it up naturally through new use cases.)

**Comment by lacco** [comment]
Wow, this is really nice and seems to work! Thank you so much!
