### ISSUE TITLE
Timezone not included in returned time objects

### ISSUE THREAD

**Issue by 23tux** [zendesk/biz#129]
Hi,

I'm not sure if this is intentional or I'm missing something. But I noticed that returned time objects from biz do not include the configured time zone:

```
Biz.configure do |config|
  config.hours = { mon: { "09:00" => "17:00" } }
  config.time_zone = "Europe/Berlin"
end

Biz.time(0, :hours).after(Time.zone.now)
=> "2018-10-15T07:00:00.000Z"
Biz.time(0, :hours).after(Time.zone.now).zone
=> "UTC"
```

Is this the intended behaviour? I could imagine in order to support multiple timezones, one could rely on a common ground of truth like the UTC time.

So, is it up to the user to convert the returned UTC times to a specific time zone, or am I doing something wrong?

**Comment by craiglittle** [comment]
> is it up to the user to convert the returned UTC times to a specific time zone

Yep! You're correct. All calculated times are returned in UTC.

**Comment by craiglittle** [comment]
@23tux I'm going to close this since I don't think there's any outstanding issue. Please let me know if there are any other questions I can help with.
