### ISSUE TITLE
Infinity loop when no hours are configured

### ISSUE THREAD

**Issue by 23tux** [zendesk/biz#130]
When you configure biz with no hours, it runs into an infinity loop

```
Biz.configure do |config|
  config.hours = { mon: {} }
end
Biz.periods.on(Date.today).first.start_time
^CInterrupt: 
from /usr/local/bundle/gems/biz-1.8.0/lib/biz/periods/abstract.rb:40:in `block in week_periods'
```

This is also the case, when you provide every day of the week, but just with an empty hash. I would expect a `nil` as the return value of `Biz.periods.on(Date.today).first` when no periods where found.

**Comment by craiglittle** [comment]
Thanks for the report! It looks like there's a hole in the validation logic. The expected behavior in this case is for a `Biz::Error::Configuration` exception to be raised.

**Comment by nmatpt** [comment]
This happens as well if you configure something like: `hours={:mon=>{"00:00"=>"00:00"}`
