### ISSUE TITLE
help! 在设置shifts之后，时长计算有误，麻烦关注一下

### ISSUE THREAD

**Issue by LongLonghaoran** [zendesk/biz#142]
这是我的biz配置:

```ruby
  Biz::Schedule.new do |config|
    config.hours = {
        mon: {'07:40' => '11:30', '12:30' => '16:40'},
        tue: {'07:40' => '11:30', '12:30' => '16:40'},
        wed: {'07:40' => '11:30', '12:30' => '16:40'},
        thu: {'07:40' => '11:30', '12:30' => '16:40'},
        fri: {'07:40' => '11:30', '12:30' => '16:40'}
    }

    config.shifts = {
        Date.new(2019, 4, 28) => {'07:40' => '11:30', '12:30' => '16:40'},
        Date.new(2019, 4, 29) => {'07:40' => '11:30', '12:30' => '16:40'},
    }
    config.time_zone = 'Asia/Shanghai'
  end

```

但是在计算时长以及判断是否为工作时段时却出错了:

```ruby
Time.parse('2019-04-29 10:00').business_hours? # 结果为 false
```

```ruby
seconds = Biz.periods.after(start_time).timeline.until(end_time).map(&:duration).reduce(Biz::Duration.new(0), :+).in_seconds.to_f  #结果为0 秒
```

**Comment by craiglittle** [comment]
Hi, @LongLonghaoran!

I used the same configuration that you specified and I wasn't able to reproduce this result once I forced the parsed time into Shanghai's time zone:
```ruby
Time.parse('2019-04-29 10:00 +0800').business_hours? # true
```
When a time zone isn't specified, a `Time::parse` defaults to using the system time zone, which I'm guessing might not have been GMT+8 at the time you created this issue.

I'm going to close the issue for now, but if you're able to continue to reproduce this behavior after accounting for the time zone difference, please give me more details and I'd be happen to reopen and take another look.
