### ISSUE TITLE
Export to schema.org OpeningHoursSpecification

### ISSUE THREAD

**Issue by 23tux** [zendesk/biz#143]
Hi,

I'd like to export opening hours into the schema.org format, see https://schema.org/OpeningHoursSpecification. Background is that I want to give Google the business hours via json+ld on my website, see https://developers.google.com/search/docs/data-types/local-business "Business Hours".

I'd be happy to try for a PR, could you give me some guidance on how and where you would implement such a feature?

**Comment by craiglittle** [comment]
Hi, @23tux! Apologies for the delayed response. :sweat_smile:

You're able to [access the underlying `biz` configuration](https://github.com/zendesk/biz/blob/master/lib/biz.rb#L19-L32) to transform it, as needed, into other schemas/formats. Unless a substantial minority of users have a need for a feature, I generally err on the side of excluding features like this to keep the gem focused, tight, and maintainable.

Please let me know if you have trouble accessing any element of the configuration and I'll see if I need to make a change to the gem's API to facilitate. I'll close this for now until I hear back.
