### ISSUE TITLE
Incorrect periods and working hours when shifts and hours fall on same day

### ISSUE THREAD

**Issue by jjalan** [zendesk/biz#145]
I am trying to create a schedule where a person works on every Thursday 9:00 a.m. - 12:00 pm. and has shifts every alternate Thursday from 1:00 p.m. - 5:00 p.m.

**Sample Code:**
```
date = Date.new(2021, 8, 5)

biz_schedule = Biz::Schedule.new do |config|
  config.hours = {
    thu: { "09:00" => "12:00" }
  }
  config.shifts = {
    Date.new(2021, 8, 5) => { "13:00" => "17:00" },
    Date.new(2021, 8, 19) => { "13:00" => "17:00" }
  }
end

hours = biz_schedule.within(
  date.beginning_of_day.utc,
  date.end_of_day.utc
).in_seconds
periods = biz_schedule.periods.on(date)&.to_a

puts "hours #{hours}"
puts "periods #{periods.inspect}"
```

**Expected:**
Every alternate Thursday (when there is a shift), I expect two periods (9 - 12, 13 - 17) and working hours to be 7 hours.

**Actual:**
Every alternate Thursday (when there is a shift), I get one period corresponding to shift (13 - 17) and working hours to be 4 hours.

```
hours 14400
periods [#<Biz::TimeSegment:0x00007fdff42c3130 @start_time=2021-08-05 13:00:00 UTC, @end_time=2021-08-05 17:00:00 UTC, @date=Thu, 05 Aug 2021>]
```

**Version:**
1.8.2

**Comment by craiglittle** [comment]
Hi, @jjalan! Thanks for the detailed message.

Correct, that behavior is [by design](https://github.com/zendesk/biz#configuration). From the `README`:
```
Shifts act as exceptions to the hours configured for a particular date; that is, if a date is configured with both hours-based intervals and shifts, the shifts are in force and the intervals are disregarded.
```
In this case, you'll want to provide the *full* set of shifts for any day with shifts. For example:
```ruby
config.shifts = {
  Date.new(2021, 8, 5) => { "09:00" => "12:00", "13:00" => "17:00" },
  Date.new(2021, 8, 19) => { "09:00" => "12:00", "13:00" => "17:00" }
}
```
