### ISSUE TITLE
How to handle cases where two schedules don't intersect at all?

### ISSUE THREAD

**Issue by bbbneo333** [zendesk/biz#146]
**Description:**
I want to check whether two schedules intersect (or overlap) with each other. I can simply use `schedule1 & schedule2`  which would return me the combined schedule which would be the intersection of the provided schedules.

**Problem:**
The intersection ability works great when schedules intersect, but when intersecting two non-overlapping, it throws following error:

```
Biz::Error::Configuration: hours not provided
```

While this is technically correct, as the non-overlapping schedules (in my case) the `hours` component didn't overlapped at all, thus resulting in an `nil` for `hours` in the resulting combined schedule. But from usability standpoint, this actually does not lets me serve my use case which is checking for overlapping schedules.

**Suggestions:**
I'm not sure what would be the implications of this, but shouldn't intersecting two completely exclusive objects should return `{}`  instead of `nil` here? I can certainly attempt to rescue the raised error in my case, but that doesn't seems efficient and fully error free at all. Can there be any other ways to do this?

Thanks!

**Comment by craiglittle** [comment]
Hey there, @bbbneo333! Thanks for using the gem and for reaching out with your question.

The issue with creating a intersected schedule with an empty set of hours versus failing hard with an exception is that an empty schedule would be functionally pointless in every scenario where it is to be used: Time calculations would always return zero, selecting a group of periods would always return an empty set, and determining whether a time was in business hours would always return false.

Now, we could implement a null object pattern within the gem for this case, but I don't know if it's worth the overhead of maintenance given the niche applicability.

With that said, here are a couple suggested approaches for your use case:
```ruby
# exception handling

def schedules_intersect?(schedule1, schedule2)
  (schedule1 & schedule2).intervals.any?
rescue Biz::Error::Configuration => error
  error.message == 'hours not provided' ? false : raise
end

schedules_intersect?(s1, s2)

# null-object pattern

class NullSchedule
  def intervals
    []
  end
end

def intersected_schedule(schedule1, schedule2)
  schedule1 & schedule2
rescue Biz::Error::Configuration => error
  error.message == 'hours not provided' ? NullSchedule.new : raise
end

intersected_schedule(s1, s2).intervals.any?
```

I'm going to close this issue for now as I don't think there's anything actionable, but please do let me know how you addressed your issue and/or if the above suggestions were helpful.
