### ISSUE TITLE
TimeZone Support

### ISSUE THREAD

**Issue by chadwtaylor** [zendesk/biz#16]
Is there a way to calculate using `in_hours?` based on the given date/time object without having to configure the time_zone for each evaluations? Showing an example would be best:

Assuming `config.time_zone = "America/Los_Angeles"` is set.

```
irb> start # start time in los angeles
=> Fri, 20 Mar 2015 15:00:00 PDT -07:00
irb> end # end time in los angeles
=> Fri, 20 Mar 2015 20:00:00 PDT -07:00

irb> Biz.in_hours?(start)
=> true
irb> Biz.in_hours?(end)
=> true
```

All good so far. Let's focus on New York; leaving the current time_zone configuration alone temporarily.

```
irb> start # start time in new york
=> Fri, 20 Mar 2015 15:00:00 EDT -04:00
irb> end # end time in new york
=> Fri, 20 Mar 2015 20:00:00 EDT -04:00

irb> Biz.in_hours?(start)
=> true
irb> Biz.in_hours?(end)
=> true # should be false
```

It would be nice to have Biz automatically adjust the time_zone configuration BASED on the given date/time object which is EDT -04:00. I had to adjust the time_zone on the fly like so:

```
irb> Biz.configure { |c| c.time_zone = "America/New_York" }
irb> Biz.in_hours?(start)
=> true
irb> Biz.in_hours?(end)
=> false # yay, that worked
```

Is there a way to have Biz automatically calculate based on the given date/time object like PDT vs EDT?

My fear is with having to do `Biz.configure { |c| c.time_zone = "America/New_York" }` would cause time zone collision when another thread needs to set it to something else causing skewed results? I appreciate any tips/advice especially when my app deals with timezones all over the world.

Lastly but not least, thanks for making this gem available to us!

**Comment by craiglittle** [comment]
Hey, @chadwtaylor! Thanks for giving the gem a try.

First, something seems off with the results of your examples.

Here's what I get for Los Angeles:
```ruby
Biz.configure { |s| s.time_zone = 'America/Los_Angeles' }

start_time = Time.use_zone('America/Los_Angeles') { Time.zone.local(2015, 3, 20, 15) }
# => Fri, 20 Mar 2015 15:00:00 PDT -07:00
end_time = Time.use_zone('America/Los_Angeles') { Time.zone.local(2015, 3, 20, 20) }
# => Fri, 20 Mar 2015 20:00:00 PDT -07:00

Biz.in_hours?(start_time)
# => true
Biz.in_hours?(end_time)
# => false
```

And for New York:
```ruby
Biz.configure { |s| s.time_zone = 'America/New_York' }

start_time = Time.use_zone('America/New_York') { Time.zone.local(2015, 3, 20, 15) }
# => Fri, 20 Mar 2015 15:00:00 EDT -04:00
end_time = Time.use_zone('America/New_York') { Time.zone.local(2015, 3, 20, 20) }
# => Fri, 20 Mar 2015 20:00:00 EDT -04:00

Biz.in_hours?(start_time)
# => true
Biz.in_hours?(end_time)
# => false
```

> Is there a way to have Biz automatically calculate based on the given date/time object like PDT vs EDT?

`biz` handles times in varying time zones seamlessly when passed as arguments. The only thing that needs to be configured is the time zone of the schedule you want those times checked against. Unlike most of the alternatives, `biz` doesn't have a dependency on `active_support`, and thus, doesn't know about Rails time objects that carry around information about their time zones.

If it's any interest, I'm planning to release an extension for Rails at some point ([`biz-rails`](https://github.com/craiglittle/biz-rails)) that would provide additional conveniences in a Rails environment.

In any case, assuming you're in a Rails environment, configuring the time zone to be used throughout a request can be done once, perhaps in a middleware.

> My fear is with having to do Biz.configure { |c| c.time_zone = "America/New_York" } would cause time zone collision when another thread needs to set it to something else causing skewed results?

Fear not, the top-level configuration is thread safe out of the box:
```ruby
(1..100).map {
  Thread.new do
    Biz.configure { |b| b.business_hours = {mon: {'09:00' => '17:00'}} }

    sleep 1

    Biz.send(:schedule).object_id
}.each(&:join).map(&:value).to_set.count
# => 100
```

If you need schedules configured with different hours and/or time zones in the same thread, just create instances of `Biz::Schedule`:
```ruby
schedule_1 = Biz::Schedule.new { |s| s.time_zone = 'America/Los_Angeles' }
schedule_2 = Biz::Schedule.new { |s| s.time_zone = 'America/New_York' }
```

I hope that points you in the right direction. I'm going to close this issue for now, but feel free to comment again if something's confusing or you think there's still an issue!

**Comment by chadwtaylor** [comment]
Hey @craiglittle, had to comment only to thank you for responding so promptly! :+1: It's just a Canadian thing. 

All is good now and thanks for sharing your examples. I know this will be very useful to others who come across this.

**Comment by craiglittle** [comment]
No problem! This actually gives me some good feedback for potential improvements we could make to the `README`.
