### ISSUE TITLE
Day calculation doesn't keep the second value

### ISSUE THREAD

**Issue by take** [zendesk/biz#21]
failing spec in https://github.com/zendesk/biz/pull/20

I guess this is a bug? :o

**Comment by craiglittle** [comment]
Whoops, duh. Thanks for the report. Fix coming momentarily!

**Comment by take** [comment]
woot thanks! :D

**Comment by craiglittle** [comment]
Closing, PR open: https://github.com/zendesk/biz/pull/22.
