### ISSUE TITLE
Hours normalization

### ISSUE THREAD

**Issue by marionzualo** [zendesk/biz#33]
While working with the gem I realized that it does not support hours in the following format:
```ruby
  {
    mon: { "22:00" => "02:00" },  # because the period spans multiple days
    wed: { "21:00" => "00:00" }  # because the end of the interval should be 24:00 instead of 00:00
  }
```
My data source has output in the form and I wanted that functionality baked in the gem so I made [some](https://github.com/marionzualo/biz/commit/469f5b9f2e1d44a50ea6650cab98eb3800bf3238) [changes](https://github.com/marionzualo/biz/commit/fd488051c0fcefb96d7208d7655c22615512e2bc) to it, which "normalize" the input before doing the processing.

I don't know if such a functionality is helpful for you therefore, I did not open a PR. Let me know if you'd like such a feature to be integrated into the gem, and I can help with that if needed.

Thanks!

**Comment by craiglittle** [comment]
Hey, @marionzualo!

I've considered making the configuration more powerful in the past, but I'm wary of the additional complexity it brings. There's something nice about keeping the configuration relatively simple and just forcing users to conform to it. For one thing, it makes for fewer places where bugs could potentially hide.

Still, one of the aspect of this gem that makes it superior to its competitors is the fact that its core engine is not bound by the concept of days. It *would* be nice to surface that power to users at the configuration layer. However, for the time being, I think I'm going to put off making that decision.

I appreciate the feed, though! I'm going to close this issue for now, but I'll certainly keep your use case in mind for future major releases of the gem.

**Comment by marionzualo** [comment]
@craiglittle Sure, I assumed that could be the case. Thanks for the swift reply!
