### ISSUE TITLE
Intersecting two Biz::Schedule

### ISSUE THREAD

**Issue by pocman** [zendesk/biz#50]
Hi, 

I would like to create `Biz::Schedule` as an intersection of two other `Biz::Schedule`.
They should have the same `time_zone`, the union of `holidays` and the intersection of `hours`.

Is that already implemented or should I do it ?
Thanks.

**Comment by craiglittle** [comment]
Hey there, @pocman!

This isn't something that's currently supported out of the box, but I think it's an interesting feature.

Let me see what I can do.

**Comment by craiglittle** [comment]
This feature has been released in [`v1.5.0`](https://rubygems.org/gems/biz/versions/1.5.0)! Let me know if you run into any issues.

**Comment by pocman** [comment]
Thanks a lot, 20 hours for a feature... 
It's going to save me a lot of pain :D

**Comment by craiglittle** [comment]
Haha, you happened to catch me at a team offsite with some free time. Glad to help! Thanks for the suggestion.
