### ISSUE TITLE
Inner rounding TimeSegments

### ISSUE THREAD

**Issue by pocman** [zendesk/biz#54]
I would like to be able to get the biggest rounded TimeSegment contained in a TimeSegment.
We should be able to round using :hour, :minute and :second.
An example for hour only :
```
    def inner_round(:hour)
      new((@start_time + 1.hour).beginning_of_hour, @end_time.beginning_of_hour)
    end
```

**Comment by craiglittle** [comment]
Could you provide specific examples with expected output?

At first glance, I'm not sure if this is something that needs to or should live in the gem itself.

**Comment by pocman** [comment]
It might be too specific.
It could be nice if TimeSegment had some kind of interval API :
* intersection (overlapping).
* union (it might be tricky for none overlapping segments).
* contains (an other segment).

**Comment by craiglittle** [comment]
Two out of the three already [exist on `TimeSegment`](https://github.com/zendesk/biz/blob/e05502faa0540bac7822d83de948e74a97e0283f/lib/biz/time_segment.rb#L34-L43). The only one that doesn't is the tricky `union`.

Does that address your use case?

**Comment by pocman** [comment]
The `contains?` seems to take a Time and not a TimeSegment.

2016-04-05 2:39 GMT+02:00 Craig Little <notifications@github.com>:

> Two out of the three already exist on TimeSegment
> <https://github.com/zendesk/biz/blob/e05502faa0540bac7822d83de948e74a97e0283f/lib/biz/time_segment.rb#L34-L43>.
> The only one that doesn't is the tricky union.
>
> Does that address your use case?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/biz/issues/54#issuecomment-205561164>
>



-- 
*Thomas Pocreau*
Recherche & Développement | *Colisweb*

thomas@colisweb.com
06 45 12 61 58
Euratechnologies | 165, Avenue de Bretagne
59000 - Lille

**Comment by craiglittle** [comment]
How about doing something like:
```ruby
ts1.endpoints.all? { |endpoint| ts2.contains?(endpoint) }
```

**Comment by pocman** [comment]
Yes, I did it this way but contains? is error prone since it returns false
when you pass a TimeSegment.

Thanks a lot for your feedback :-)

**Comment by craiglittle** [comment]
No problem! Yeah, unfortunately, that's sort of the nature of weakly typed languages like Ruby. Without adding a bunch of type checks everywhere, one must understand what the method expects to receive. At least it didn't return true every time, eh? :)

I'll definitely keep this use case in mind in case I hear similar needs from other users, but I'm going to close the issue for now. Thanks for putting the gem through its paces! Please let me know if you run into anything else.
