### ISSUE TITLE
ForDuration calculation with 0 raises error

### ISSUE THREAD

**Issue by mwean** [zendesk/biz#59]
I just ran into an issue where I tried to calculate 0 days after a given time, and got an error.

```ruby
schedule = Biz::Schedule.new do |config|
  config.hours = {
    mon: { '07:00' => '18:00' },
    tue: { '07:00' => '18:00' },
    wed: { '07:00' => '18:00' },
    thu: { '07:00' => '18:00' },
    fri: { '07:00' => '18:00' }
  }
end

Biz::Calculation::ForDuration.days(schedule, 0).after(Time.now)
NoMethodError: undefined method `year' for nil:NilClass
from /Users/Matt/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/biz-1.5.1/lib/biz/time.rb:80:in `on_date'
```

It looks like the issue is [here](https://github.com/craiglittle/clavius/blob/master/lib/clavius/calculation/days_from.rb#L15):

```ruby
def after(date)
  schedule.after(date).take(number_of_days).to_a.last
end
```

Where it's taking 0 from the array. Is this a case you would like to handle? If not, it might be good to add a descriptive error, because it took a little while to hunt down the problem.

**Comment by craiglittle** [comment]
Thanks for the report!

Descriptive error on the way: https://github.com/zendesk/biz/pull/60
