### ISSUE TITLE
Times as Holidays?

### ISSUE THREAD

**Issue by chrismahon** [zendesk/biz#64]
Hi Craig, firstly thanks for this gem really loving it so far.

I do have a question relating to holidays though. Is it possible to have a Time or Period as a holiday instead of the whole Day/Date?

I'm trying to use the gem as time slots for individual members of staff. As an example, a staff member might be booked between 9:00am–9:30am and 2:00pm–2:15pm, I was thinking I could use the holidays functionality within the gem to to add those time slots as "holidays" so that I could find the next available working hour for that member of staff.

Hope this makes sense?

Thanks,
Chris

**Comment by craiglittle** [comment]
Welcome, @chrismahon. Glad you're enjoying the gem!

That's an interesting idea, and I think it could integrate into the period-generation logic relatively seamlessly. Let me dig into it a bit more and see what it would look like.

**Comment by craiglittle** [comment]
@chrismahon Just wanted to give you a heads up that this feature has been released in [`v1.6.0`](https://rubygems.org/gems/biz)! See the `README` for details.
