### ISSUE TITLE
How to handle 24 hours setup?

### ISSUE THREAD

**Issue by aserafin** [zendesk/biz#68]
Hi, 

I'm wondering how you would suggest handling 24h working day? Is this the way to go:

```
config.hours = {
   mon: { "00:00": "23:59" }
}
```

If yes, then 23:59:10 would be consider open or closed?

**Comment by craiglittle** [comment]
Hey, @aserafin!

This is how you'd do it:
```ruby
Schedule.new do |config|
  config.hours = {mon: {'00:00' => '24:00'}}
end
```

> If yes, then 23:59:10 would be consider open or closed?

All times up to the second midnight are considered open. The exact moment of the second midnight isn't considered open by default, but you can [write your own wrapper to change that behavior](https://github.com/zendesk/biz/issues/62), if you'd like.

**Comment by aserafin** [comment]
Great, thanks!
