### ISSUE TITLE
in_hours? doesn't consider breaks

### ISSUE THREAD

**Issue by aserafin** [zendesk/biz#69]
Hi, 

It looks like `in_hours?` implementation doesn't consider breaks. I think this change in the in the `lib/biz/calculation/active.rb` will fix it: 

```
def result
  schedule.intervals.any? { |interval| interval.contains?(time) } &&
    schedule.breaks.none? { |b| b.contains?(time) } &&
    schedule.holidays.none? { |holiday| holiday.contains?(time) }
end
```

but before creating pull-request I want to make sure that this isn't somehow intentional?

**Comment by craiglittle** [comment]
Good catch! No worries, I've opened a PR: https://github.com/zendesk/biz/pull/70.
