### ISSUE TITLE
Bug with Biz.time(...).before(...) calculations

### ISSUE THREAD

**Issue by aserafin** [zendesk/biz#73]
Hi, 

Given this configuration

```ruby
schedule = Biz::Schedule.new do |config| 
  config.hours = {
    mon: { '09:30' => '16:00' },
    tue: { '09:30' => '16:00' },
    wed: { '09:30' => '16:00' },
    thu: { '09:30' => '16:00' },
    fri: { '09:30' => '16:00' }
  }
  config.holidays = []
  config.breaks = {}
  config.time_zone = 'America/New_York'
end

sunday_beginning_of_the_day = ActiveSupport::TimeZone.new('America/New_York').local(2016,6,12,0,1,0)
sunday_end_of_the_day = ActiveSupport::TimeZone.new('America/New_York').local(2016,6,12,23,59,0)

puts schedule.time(1, :day).before(sunday_beginning_of_the_day)
puts schedule.time(1, :day).before(sunday_end_of_the_day)
```

it will print two different days
```
2016-06-09 20:00:00 UTC
2016-06-10 20:00:00 UTC
```

and since `Sunday` is free day then it should return the same day (thursday or friday it's debatable) regarding what hour we pass.

I dig a little and in `for_duration.rb` file the `advanced_time` returns Friday both times but with different hours and then the periods calculation happen and the problem seems to be somewhere there.

**Comment by aserafin** [comment]
Just found issue #56 - your explanation makes total sense once you read it

> Find the next day that contains business hours. Starting from the same minute on that day as the specified time, look forward (or back) to find the next moment in time that is in business hours.

Maybe we should move it to the readme in separate section `How day calculations work` to avoid confusion?

**Comment by craiglittle** [comment]
> Maybe we should move it to the readme in separate section f.e.: How day calculations work to avoid confusion?

Seems reasonable to me. Added in https://github.com/zendesk/biz/pull/74.

**Comment by aserafin** [comment]
Awesome - thank you!
