### ISSUE TITLE
How to calculate the "next business day"?

### ISSUE THREAD

**Issue by vraravam** [zendesk/biz#82]
@craiglittle - I was using `first_business_day` from the `business_time` gem when using the other gem. Thanks for pointing it out in the other issue. In this one, how can I achieve the same?

**Comment by craiglittle** [comment]
Welcome, @vraravam!

If you're looking for a `Time` object as the result, do the following:
```ruby
Biz.time(1, :day).after(Time.now)
```

For a `Date` object:
```ruby
Biz.dates.days(1).after(Time.now)
```

Hope that's helpful!

**Comment by craiglittle** [comment]
I'm going to close this issue for now. Please let me know if you have any other questions, though!
