### ISSUE TITLE
Creating empty Biz::Schedule

### ISSUE THREAD

**Issue by pocman** [zendesk/biz#86]
Hi, 

before 1.6.0, I was using 
```
    Biz::Schedule.new do |config|
      config.hours = {mon:{"00:00"=>"00:00"}}
      config.breaks = {}
      config.holidays = []
      config.time_zone = "Europe/Paris"
    end
```
but now, it leads to infinite loop when calling `#within` on this Schedule.
Could you provide a simple way to generate an empty Schedule ?

**Comment by guizmaii** [comment]
`Biz::Schedule.empty` ?

**Comment by pocman** [comment]
In fact, the bug is even weirder than that : 
```
    b = Biz::Schedule.new do |config|
      config.hours = {mon:{"00:00"=>"00:00"}}
      config.breaks = {}
      config.holidays = []
      config.time_zone = "Europe/Paris"
    end
    b.within(Time.now.in_time_zone("Europe/Paris"), (Time.now+1.day).in_time_zone("Europe/Paris")) #working
    b.within(Time.now.utc, (Time.now+1.day).utc) #Not working
```

**Comment by craiglittle** [comment]
Thanks for the report! I'll figure out what's going on when I have a bit of time.

**Comment by craiglittle** [comment]
@pocman This no longer works because we had to reject empty intervals to avoid an potential obscure DST bug.

Could you explain your use case more? Could you create a "null schedule" object that conforms to the `biz` API instead?

**Comment by pocman** [comment]
@craiglittle that is exactly what I want : an empty (no hours) schedule that implement `biz` api.
`Biz::Schedule.empty` would be great. I thought it was possible to create an empty schedule using `Biz::Schedule.new`.

**Comment by craiglittle** [comment]
Looking at it more, building this feature is going to introduce a decent amount of complexity for a small use case. I'm more inclined to throw a clearer error when you try to configure a schedule without any hours.

Instead of relying on `biz` to generate a "null" schedule, why not create your own null object for your use case? Just have it always return zero when you call `within`, right?

**Comment by craiglittle** [comment]
This isn't going to be behavior we're going to explicitly support at this time, but I'll keep an open mind if I hear similar use cases in the future. In the meantime, I'd suggest writing your own null object that fits your needs.

**Comment by pocman** [comment]
Thanks :-)

**Comment by a-stroyevskiy** [comment]
I also would like to have empty schedule for new users.
I think this is normal case, when new user register in application and has empty schedule and can configure it with UI in future.
